### ISSUE TITLE
is there a plan for arduino mqtt-sn-tools like client

### ISSUE THREAD

**Issue by psprajc** [njh/mqtt-sn-tools#19]
mqtt-sn-tools works great with rpi (RSMB)  to rpi comunication (mqtt-sn-tools) over cheap rf24 radios.

It would be great to use your library with cheap rf24 radio together with RF24ethernet library on arduino.

**Comment by njh** [comment]
No, it will always just be command line tools for POSIX, not a library.

The Paho project provides a embedded library that could be used with Arduino:
https://eclipse.org/paho/clients/c/embedded-sn/

**Comment by njh** [comment]
See also my MQTT-SN QoS -1 publisher:
https://github.com/njh/DangerMinusOne/blob/master/DangerMinusOne.ino
