### ISSUE TITLE
how get started

### ISSUE THREAD

**Issue by mgiaco** [njh/mqtt-sn-tools#20]
Hello Nicholas,

Can you explain how to use this tools? I think i understand the pub and sub tools but which mqtt-sn broker or mqtt-sn gateway are you using.

thanks for your help

**Comment by mgiaco** [comment]
Okay i found your ruby gateway and now it works with mosquito as the broker. So but how to use the dump in this scenario because i cannot bind a to the UDP socket because the gateway use it so how to use the dump tool?

Do you know any other mqtt-sn gateway for the raspberry?

thx 
mathias

**Comment by njh** [comment]
Hello,

My ruby gateway is fairly incomplete. The RSMB has complete MQTT-SN support:
http://modelbasedtesting.co.uk/?p=44

This is the configuration that I use with it:
https://gist.github.com/njh/1d3c76b55719910263ca

The dump tool is probably only useful on its own for QoS -1.
It is more useful when combined with a some other tool to capture and relay packets.

nick.

**Comment by mgiaco** [comment]
Hello,

Thanks for your help. Then I will switch to the RSMB implementation. But can I use these tools for some tests? Or would you say that they are also incomplete? 

I want to test your sample publisher.
>>See also my MQTT-SN QoS -1 publisher:
>>https://github.com/njh/DangerMinusOne/blob/master/DangerMinusOne.ino

So I thought I could use your serial bridge and your gateway. So for the gateway I will check out some code in the rsmb repo. But can I use the serial bridge for some firt tests or ist this also incomplete? 
I would like to create a simple working example before I start to implement all that stuff on an cortex m4.

thanks for your help thats really great
mahias
