### ISSUE TITLE
Build error for Embedded ARM devices

### ISSUE THREAD

**Issue by hkolasani** [njh/mqtt-sn-tools#21]
Hi,

The tool set works great in my mac connecting to an RSMB. But when I tried to build a mqtt client code using your mutt-sn.c for a Marvel micro controller, I get the following error. I am using GNU ARM GCC from https://launchpad.net/gcc-arm-embedded.
## The error:-

mqtt-sn.c:29:24: fatal error: sys/socket.h: No such file or directory

Appreciate any kind of assistance with a resolution or a work-around.

Regards

**Comment by njh** [comment]
Hi,

Do you know why sys/socket.h doesn't exist on ARM?

Thanks,

nick.

**Comment by hkolasani** [comment]
Thank you so much for the prompt response. I am a novice when it comes to embedded OS. Tried to google the issue and it looks like the cross compiler that I am using for ARM is bare metal and may not support those libraries. Also, I came across lip (http://savannah.nongnu.org/projects/lwip/) which seems to have their own sockets.h but I couldn't built mqtt-sn.c even with those libraries.

**Comment by njh** [comment]
Sorry, I don't have any experience with cross-compiling code for ARM on bare metal.

Have you been able to compile other network code for Marvel?

**Comment by hkolasani** [comment]
Yes. I got this AWS Starter kit for Marvel which has some AWS MQTT specific code and that seems to work fine. I noticed that they were using using a 'posix/sys/socket.h' and some lwip code as I mentioned above. I tired to use that for MQTT-SN.c and couldn't go very far.

**Comment by hkolasani** [comment]
Here is the link to the aws mqtt code for the Marvel kit. https://github.com/marvell-iot/aws_starter_sdk

**Comment by njh** [comment]
Sorry, I don't have a AWS Starter kit for Marvel, so I am unlikely to be able to help you.

You might have more success asking was is required to get a generic Unix programme to work on Marvel.
