### ISSUE TITLE
How to start using mqtt-sn-tools?

### ISSUE THREAD

**Issue by PriTechIoT** [njh/mqtt-sn-tools#22]
Hello,
I am trying to implement mqtt-sn to communicate BLE over internet. I am very new to working with MQTT-SN protocol. I have read the guide to use RSMB broker. I have installed RSMB broker to my PC. I don't know how to use mqtt-sn- tools. I have read this article also: [http://modelbasedtesting.co.uk/2013/11/24/getting-started-with-mqtt-sn-in-rsmb/] but not getting complete idea about to use mqtt-sn with RSMB for publish and subscription.
It will be really helpful for me if anyone can help. Thanks in advance. :)
Please help!

**Comment by njh** [comment]
What have you tried so far?

**Comment by PriTechIoT** [comment]
I have made my PC as a server with RSMB broker and start bridging the connection between MQTT-SN and mosquitto MQTT broker.

**Comment by njh** [comment]
What commands are you typed in?
What didn't work?
Do you already have normal MQTT working?

There is quite a good article on how to ask for help here:
https://stackoverflow.com/help/how-to-ask

**Comment by njh** [comment]
No, response, closing issue.
