### ISSUE TITLE
How do I use MQTT-SN without a gateway?

### ISSUE THREAD

**Issue by nabilmakarem** [njh/mqtt-sn-tools#29]
Hello,
I download the repository to my ubunutu PC. Then I ran make then make install respectively. 

I started the mqtt-sn-dump using:
- mqtt-sn-dump -d -p 1888

However, when I publish or subscribe using:
1- mqtt-sn-pub -p 1888 -h 127.0.0.1 -t test -m "1" 
2-  mqtt-sn-sub -p 1888  -h 127.0.0.1 -t test

I receive the error that I am failed to connect to mqtt-sn gateway.

I also tried to run: 
mqtt-sn-serial-bridge -h localhost -p 1888
but it gave me: missing serial port (this is obvious as I do not have serial ports)

Please let me know if you can help me solve this issue as I need to test mqtt-sn.

Regards,
Nabil M.

**Comment by njh** [comment]
Hi Nabil,

Which MQTT-SN Gateway or Server are you using with `mqtt-sn-tools`?

mqtt-sn-dump / mqtt-sn-pub can be used standalone with with QoS -1 ('fire and forget') - which just sends a single publish packet without establishing a connection.

This is working for me:

```
~ $ mqtt-sn-dump -p 1888 -d -v
2018-05-27 14:39:06 DEBUG Debug level is: 1.
2018-05-27 14:39:06 DEBUG Verbose level is: 1.
2018-05-27 14:39:06 DEBUG mqtt-sn-dump listening on port 1888
2018-05-27 14:39:09 DEBUG waiting for packet...
2018-05-27 14:39:09 DEBUG Received  8 bytes from 127.0.0.1:63334. Type=PUBLISH on Socket: 3
SH: 1
```

```
~ $ mqtt-sn-pub -p 1888 -h 127.0.0.1 -t SH  -m "1" -q -1 -d
2018-05-27 14:39:09 DEBUG Debug level is: 1.
2018-05-27 14:39:09 DEBUG Sending PUBLISH packet...
```


Note also with QoS -1, you can't use full topic names. You can either use short topic names (two characters long) or pre-defined topic ids (16-bit number).


nick.

**Comment by nabilmakarem** [comment]
Hello,


Thank you for your prompt reply.


Kindly note the example you provided works as well on my linux server. The dump gets messages from publisher.


However, when I try to subscribe to a topic using:

 mqtt-sn-sub -p 1888 -h 127.0.0.1 -t SH -d

I receive the error:

ERROR Failed to connect to MQTT-SN gateway.

I am currently working on MQTT-SN as standalone without any gateway. I already have mosquitto for mqtt but I need to study the performance of using mqtt-sn only.

Kindly advise.

regards,
Nabil M.


________________________________

**Comment by njh** [comment]
With MQTT-SN you need either a Server (aka Broker) that supports MQTT-SN or a Gateway.

> MQTT-SN requires a MQTT-SN Gateway which acts as a protocol converter to convert MQTT-SN messages to MQTT messages. MQTT-SN client (UDP) can not communicate directly with MQTT broker(TCP/IP).


It looks like EMQ supports MQTT-SN:
http://emqtt.io/docs/v2/mqtt-sn.html

RSMB is is a legacy server but supports MQTT-SN:
https://github.com/eclipse/mosquitto.rsmb

Or use a gateway to convert between MQTT-SN and MQTT:
https://www.eclipse.org/paho/components/mqtt-sn-transparent-gateway/


I am not sure what made you think that MQTT-SN could be used standalone without any gateway?

**Comment by nabilmakarem** [comment]
Hello again,

Well the main reason is that I am doing some studies on MQTT and MQTT-SN.

I installed mosquitto for mqtt which has broker, pub and sub. I checked the code you did and I thought it does the same but I then noticed it needs a gateway. Do you know any platform where I can fully test mqtt-sn like the ones for mqtt as a totally standalone??


Thank you,
Nabil M.

**Comment by njh** [comment]
The MQTT-SN specification is here:
http://mqtt.org/new/wp-content/uploads/2009/06/MQTT-SN_spec_v1.2.pdf

But it does not specify any mechanism for publishing and subscribing without either a MQTT-SN Gateway or Server.

It might be possible to send MQTT-SN PUBLISH packets with a QoS of -1 to a multicast address. But that isn't part of any specification. Also if there was any packet loss (particularly a problem on wireless networks), then messages would go missing.
