### ISSUE TITLE
Support for larger than 256 byte length packets

### ISSUE THREAD

**Issue by PureEngineering** [njh/mqtt-sn-tools#32]
support for the full Length of mqtt-sn spec. Right now only the 1 byte long octet is supported.  

bellow is from the mqtt-sn spec. 

The Length field is either 1- or 3-octet long and specifies the total number of octets contained in the message (including the Length field itself).
If the first octet of the Length field is coded “0x01” then the Length field is 3-octet long; in this case, the two following octets specify the total number of octets of the message (most-significant octet first). Otherwise, the Length field is only 1-octet long and specifies itself the total number of octets contained in the message. The 3-octet format allows the encoding of message lengths up to 65535 octets. Messages with lengths smaller than 256 octets may use the shorter 1-octet format.
Note that because MQTT-SN does not support message fragmentation and reassembly, the maximum message length that could be used in a network is governed by the maximum packet size that is supported by that network, and not by the maximum length that could be encoded by MQTT-SN.

**Comment by njh** [comment]
"Packets must be 255 or less bytes long" is listed as being one of the limitations in the mqtt-sn-tools README.

Is this a request to change that?

**Comment by njh** [comment]
Sorry I don't intend to add support for packets longer than 255 bytes.

I have always intended to try and keep this set of tools lightweight and simple.
It has got a bit more complex than I had first planned but adding support for more than 255 bytes would require considerable work.
