### ISSUE TITLE
I have a problem with my MQTT-SN gateway

### ISSUE THREAD

**Issue by kevin0598** [njh/mqtt-sn-tools#38]
it seem i can't use my MQTT-SN tools

![image](https://user-images.githubusercontent.com/48360957/81211801-7f68ce80-9006-11ea-8028-c7c84ca54c84.png)

but i already use Mosquitto broker as my gateway is there any problem that i missing?
![image](https://user-images.githubusercontent.com/48360957/81211833-8c85bd80-9006-11ea-9fea-60b9d96baa84.png)

**Comment by njh** [comment]
Mosquitto does not support MQTT-SN, you need to use it with a MQTT-SN -> MQTT Gateway:
https://www.eclipse.org/paho/components/mqtt-sn-transparent-gateway/
