### ISSUE TITLE
incorrect in-order expectations with non clean session

### ISSUE THREAD

**Issue by aep** [njh/mqtt-sn-tools#4]
when not setting clean-session, the broker may answer a CONNECT with the previous subscriptions as REGISTER message, as specified in MQTT-SN_spec_v1.2.pdf  paragraph 6.10.

however, mqtt-sn-sub espects SUBSCRIBE to be immediately followed by SUBACK and dies on any message left in the brokers queue. This will probably happen with a leftover PUBLISH as well.

    ./mqtt-sn-sub -d -t foo -1  -i blabla -c
    Sending CONNECT packet...
    waiting for packet...
    Received 3 bytes. Type=CONNACK.
    CONNACK return code: 0x00
    Sending SUBSCRIBE packet...
    waiting for packet...
    Received 13 bytes. Type=REGISTER.
    Was expecting SUBACK packet but received: 0x0a

a

**Comment by njh** [comment]
Thanks for reporting... not quite sure how I'm going to fix this yet!

Think it may require having a packet buffer, so that they can be processed out of order.

**Comment by njh** [comment]
This should be fixed now - mqtt-sn-sub should cope with the server sending both Register and Publish packets straight after the Connack.

Do you mind double checking?
