### ISSUE TITLE
What is the problem with this?

### ISSUE THREAD

**Issue by kevin0598** [njh/mqtt-sn-tools#40]
i don't know what happen but suddenly this error came up eventhough 2 hours ago i success implement MQTT-SN Client
![image](https://user-images.githubusercontent.com/48360957/81405165-b4d9fd00-9169-11ea-98fe-6cd8163f1f9c.png)

**Comment by njh** [comment]
This is a screenshot of an issue someone else reported - #39

**Comment by kevin0598** [comment]
Sorry sir,it seem i want to screenshot another picture but that picture is the one that came out and i already finished my problem that's why i closed it
i want to delete it because it's my mistake but i don't know why

I'm really sorry Sir
