### ISSUE TITLE
How can i sent data from sensor using this mqtt-sn client?? 

### ISSUE THREAD

**Issue by kevin0598** [njh/mqtt-sn-tools#41]
I want to ask, i already implemented this as my mqtt-sn client, paho.embedded-c as my mqtt-sn gateway dan mosquito as my broker

So the thing is i want to send data from sensor PIR, can i use this mqtt-sn client to send some data from sensor? If can, can you tell me how can i do that with this mqtt-sn client??

**Comment by njh** [comment]
Sorry, I can't tell you how to build your application. It mostly has little to do with MQTT-SN.

To send a message to the gateway you can use:

```
mqtt-sn-pub -h gateway.example.com -t 'sensors/pir/2' -m 'trigger'
```

**Comment by kevin0598** [comment]
-t 'sensor/pir/2'

is this how to declare that i have PIR sensor or just make some topic??

-m 'trigger'

what is the mean of triggrer? i mean what should i type? or this is command to make sensor PIR work?

**Comment by njh** [comment]
As with normal MQTT, the topic name (`-t`) can be whatever you want it to be.

The message body (`-m`) can also be whatever you want it to be. I made up the word trigger, because it seemed like a sensible word to use for what a PIR does.

**Comment by kevin0598** [comment]
Thank you Sir, so i can assume that is it possible send data from PIR sensor using this MQTT-SN clien to the gateway right? it depent on my opic and message
