### ISSUE TITLE
sending binary file with mqtt-sn-pub sends all 0

### ISSUE THREAD

**Issue by saumilsdk** [njh/mqtt-sn-tools#43]
I have to publish binary message using mqtt-sn tools using below command. But i receive all data as 0 value.

`./mqtt-sn-pub -h 54.188.130.XX -p 1883 -t topic1 -f packet_raw_000.dat`

**Comment by njh** [comment]
The problem was that the payload was being copied using `strncpy`, which meant it stopped copying when it came with a null byte.

Fixed in #45 

Thanks @saumilsdk 👍
