### ISSUE TITLE
Packets must be 255 or less bytes long

### ISSUE THREAD

**Issue by saumilsdk** [njh/mqtt-sn-tools#47]
"Packets must be 255 or less bytes long" is mentioned in the readme file. Is it true?

**Comment by njh** [comment]
Yes, it is. The protocol supports more, but this implementation doesn't.

**Comment by saumilsdk** [comment]
@njh I have tried giving more than 255 bytes using -f (file) option and it works with that.

**Comment by njh** [comment]
Sounds like a bug - pretty sure that would result in a buffer overrun.

Please can you provide an example file and the command?

**Comment by saumilsdk** [comment]
You are right. i just noticed it is not >255. Sorry for the confusion.
