### ISSUE TITLE
Message format not descibed?

### ISSUE THREAD

**Issue by pfostenberg** [njh/mqtt-sn-tools#50]
Hi,
in the documentation I found.
-m <message>   Message payload to send.

Is the message format ASCII (7 bit/8bit) UTF8? 
Or can I also pass a hex string? "0102" or 0x01 0x02 ? 

Some more explanation / example would be nice and help other users.

Reason: I have to send protobuf data to a MQTT-SN gateway and want to test this on the command line.

Or if the only way to send binary data with the -f (file) option?

BR

Andreas

**Comment by njh** [comment]
You can pass in any null terminated string of bytes using the `-m` option. What you can pass in on the command line is the same as any other Unix command line tool - there is no special handling. Note that the NULL on the end of the string won't be transmitted. This also means that your binary sequence cannot contain NULL bytes.

One way you can generate binary sequences is by using bash/echo:
```
echo -ne "\x45\x23\x43" | mqtt-sn-pub -t 'test/binary' -s
```

If you need to send byte sequences that contain nulls, then I think using the `-f` option may be the only way with this tool.

**Comment by njh** [comment]
See also:
https://stackoverflow.com/questions/37149336/how-to-send-binary-data
